In [2]:
import pandas as pd
import numpy as np

In [ ]:
df_order_reviews = pd.read_csv('../data/raw/olist_order_reviews_dataset.csv')
df_order_reviews.head()

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

In [4]:
df_order_reviews['count_chars_title'] = (
    df_order_reviews['review_comment_title']
    .str.len()
    .fillna(0)
    .astype(int)
)

df_order_reviews['count_words_title'] = (
    df_order_reviews['review_comment_title']
    .str.split()
    .str.len()
    .fillna(0)
    .astype(int)
)

df_order_reviews['count_chars_reviews'] = (
    df_order_reviews['review_comment_message']
    .str.len()
    .fillna(0)
    .astype(int)
)

df_order_reviews['count_words_reviews'] = (
    df_order_reviews['review_comment_message']
    .str.split()
    .str.len()
    .fillna(0)
    .astype(int)
)

df_order_reviews

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp,count_chars_title,count_words_title,count_chars_reviews,count_words_reviews
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59,0,0,0,0
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13,0,0,0,0
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24,0,0,0,0
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06,0,0,37,6
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53,0,0,100,15
...,...,...,...,...,...,...,...,...,...,...,...
99219,574ed12dd733e5fa530cfd4bbf39d7c9,2a8c23fee101d4d5662fa670396eb8da,5,NaN,NaN,2018-07-07 00:00:00,2018-07-14 17:18:30,0,0,0,0
99220,f3897127253a9592a73be9bdfdf4ed7a,22ec9f0669f784db00fa86d035cf8602,5,NaN,NaN,2017-12-09 00:00:00,2017-12-11 20:06:42,0,0,0,0
99221,b3de70c89b1510c4cd3d0649fd302472,55d4004744368f5571d1f590031933e4,5,NaN,"Excelente mochila, entrega super rápida. Super...",2018-03-22 00:00:00,2018-03-23 09:10:43,0,0,67,9
99222,1adeb9d84d72fe4e337617733eb85149,7725825d039fc1f0ceb7635e3f7d9206,4,NaN,NaN,2018-07-01 00:00:00,2018-07-02 12:59:13,0,0,0,0
99223,efe49f1d6f951dd88b51e6ccd4cc548f,90531360ecb1eec2a1fbb265a0db0508,1,NaN,"meu produto chegou e ja tenho que devolver, po...",2017-07-03 00:00:00,2017-07-03 21:01:49,0,0,85,16

In [5]:
df_order_reviews[(df_order_reviews['count_chars_reviews'] > 0) & (df_order_reviews['count_words_title'] > 3)]

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp,count_chars_title,count_words_title,count_chars_reviews,count_words_reviews
19,373cbeecea8286a2b66c97b1b157ec46,583174fbe37d3d5f0d6661be3aad1786,1,Não chegou meu produto,Péssimo,2018-08-15 00:00:00,2018-08-15 04:10:37,23,4,7,1
190,c40a6b6e0181e5ec0d12cbc2e12c49d3,f3468d6a2c7586711e9952242898aad4,1,falta de produto e quebra,Faltou 1 produto e os que recebi 1 veio quebrado,2018-05-23 00:00:00,2018-05-23 22:23:00,25,5,48,10
253,65b934c20d632fc2df0fd4723464fa78,824d9780d0313771024a0c70fe9dd9a7,3,Erraram na caixa acústica,"Apesar de ter sido entregue rapidamente, subst...",2018-06-12 00:00:00,2018-06-12 22:36:18,25,4,195,30
394,5c1ba09de5c746017d406bd2cfefeca3,327eb42fa668b532239f44713415a37a,3,nao entrega do produto,recebe apenas 01 peça do produto! estou precis...,2018-04-26 00:00:00,2018-04-26 13:36:47,22,4,72,12
535,19910e37f2130c56f553edfbdc0c65fb,00b12f4674177ef40c4bdb034138c843,5,Ótimo custo x benefício,Produto chegou dentro do prazo. Veio conforme ...,2018-07-21 00:00:00,2018-07-24 13:29:35,23,4,70,11
...,...,...,...,...,...,...,...,...,...,...,...
98956,44380245bf1a49875542ea0e7f216986,98efe48952662e6a45a1dc51770039d2,1,não recebi o produto aind,assim que receber produto eu avalio positivo,2018-06-26 00:00:00,2018-06-28 19:06:42,25,5,44,7
99013,d674cf343001412671d6b707b919ffd1,88d95fe1b916ad9ae117e52dd078e0fb,3,Cobrança de frete indevid,Sou cliente prime é mesmo assim me cobraram o ...,2018-07-12 00:00:00,2018-07-15 00:15:28,25,4,53,10
99104,bc21c710c4a13549093961445df5b3ba,83b38224c814740db730aad1c72c7a3f,3,Não posso recomendar aind,O Produto veio com defeito.,2018-08-14 00:00:00,2018-08-15 12:01:54,25,4,27,5
99117,61249dd0992d25082ab94464a2a47668,2437dfd68fb453ad27e1898c8b1fe868,2,Rápido porém não bom,Eu recebi o produto no prazo porém já veio lig...,2018-07-28 00:00:00,2018-07-29 02:14:59,20,4,97,19
99197,51de4e06a6b701cb2be47ea0e689437b,b7467ae483dbe956fe9acdf0b1e6e3f4,3,Não foi entregue o pedido,Bom dia \r\nDas 6 unidades compradas só recebi...,2018-06-05 00:00:00,2018-06-06 10:52:19,25,5,83,14

## Filtrar reviews sem conteúdo

In [6]:
is_empty_title = df_order_reviews['review_comment_title'].isna() | (df_order_reviews['review_comment_title'].astype(str).str.strip() == '')
is_empty_msg = df_order_reviews['review_comment_message'].isna() | (df_order_reviews['review_comment_message'].astype(str).str.strip() == '')

In [7]:
df_order_reviews_treated = df_order_reviews[~(is_empty_title & is_empty_msg)]
df_order_reviews_treated

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp,count_chars_title,count_words_title,count_chars_reviews,count_words_reviews
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06,0,0,37,6
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53,0,0,100,15
9,8670d52e15e00043ae7de4c01cc2fe06,b9bf720beb4ab3728760088589c62129,4,recomendo,aparelho eficiente. no site a marca do aparelh...,2018-05-22 00:00:00,2018-05-23 16:45:47,9,1,174,30
12,4b49719c8a200003f700d3d986ea1a19,9d6f15f95d01e79bd1349cc208361f09,4,NaN,"Mas um pouco ,travando...pelo valor ta Boa.\r\n",2018-02-16 00:00:00,2018-02-20 10:52:22,0,0,45,7
15,3948b09f7c818e2d86c9a546758b2335,e51478e7e277a83743b6f9991dbfa3fb,5,Super recomendo,"Vendedor confiável, produto ok e entrega antes...",2018-05-23 00:00:00,2018-05-24 03:00:01,15,2,56,9
...,...,...,...,...,...,...,...,...,...,...,...
99205,98fffa80dc9acbde7388bef1600f3b15,d398e9c82363c12527f71801bf0e6100,4,NaN,para este produto recebi de acordo com a compr...,2017-11-29 00:00:00,2017-11-30 15:52:51,0,0,58,10
99208,df5fae90e85354241d5d64a8955b2b09,509b86c65fe4e2ad5b96408cfef9755e,5,NaN,Entregou dentro do prazo. O produto chegou em ...,2018-02-07 00:00:00,2018-02-19 19:47:23,0,0,91,13
99215,a709d176f59bc3af77f4149c96bae357,d5cb12269711bd1eaf7eed8fd32a7c95,3,NaN,"O produto não foi enviado com NF, não existe v...",2018-05-19 00:00:00,2018-05-20 21:51:06,0,0,125,25
99221,b3de70c89b1510c4cd3d0649fd302472,55d4004744368f5571d1f590031933e4,5,NaN,"Excelente mochila, entrega super rápida. Super...",2018-03-22 00:00:00,2018-03-23 09:10:43,0,0,67,9
99223,efe49f1d6f951dd88b51e6ccd4cc548f,90531360ecb1eec2a1fbb265a0db0508,1,NaN,"meu produto chegou e ja tenho que devolver, po...",2017-07-03 00:00:00,2017-07-03 21:01:49,0,0,85,16